### ISSUE TITLE
combine org and repo in a single flag

### ISSUE THREAD

**Issue by fcurella** [pcarn/rename-github-default-branch#1]
Instead of calling `-o pcarn -r my-repo`, we could just use `-r pcarn/my-repo`, and make it more user-friendly with one less option

**Comment by pcarn** [comment]
I had wanted to call out the fact that we need the org as well, but I agree it would be more user-friendly and simpler to combine them. It will be obvious if it fails without the org.

https://github.com/pcarn/rename-github-default-branch/commit/e600b520486233d32280eb71d413de89d735c79d
